//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMatik_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Konu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Konu()
        {
            this.Sorus = new HashSet<Soru>();
        }
    
        public int Id { get; set; }
        public string Ad { get; set; }
        public int DersId { get; set; }
    
        public virtual Der Der { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Soru> Sorus { get; set; }
    }
}
