//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMatik_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soru
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Soru()
        {
            this.SoruSeceneks = new HashSet<SoruSecenek>();
            this.SoruSinavSeceneks = new HashSet<SoruSinavSecenek>();
        }
    
        public int Id { get; set; }
        public string Metin { get; set; }
        public string EkMetin { get; set; }
        public int KonuId { get; set; }
        public byte Seviye { get; set; }
    
        public virtual Konu Konu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoruSecenek> SoruSeceneks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoruSinavSecenek> SoruSinavSeceneks { get; set; }
    }
}
