//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMatik_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoruSinavSecenek
    {
        public int Id { get; set; }
        public int SinavId { get; set; }
        public int SoruId { get; set; }
        public int A { get; set; }
        public int B { get; set; }
        public int C { get; set; }
        public int D { get; set; }
        public Nullable<int> E { get; set; }
        public byte DogruSecenekSira { get; set; }
    
        public virtual Sinav Sinav { get; set; }
        public virtual Soru Soru { get; set; }
        public virtual SoruSecenek SoruSecenek { get; set; }
        public virtual SoruSecenek SoruSecenek1 { get; set; }
        public virtual SoruSecenek SoruSecenek2 { get; set; }
        public virtual SoruSecenek SoruSecenek3 { get; set; }
        public virtual SoruSecenek SoruSecenek4 { get; set; }
    }
}
