//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMatik_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoruSecenek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoruSecenek()
        {
            this.SoruSinavSeceneks = new HashSet<SoruSinavSecenek>();
            this.SoruSinavSeceneks1 = new HashSet<SoruSinavSecenek>();
            this.SoruSinavSeceneks2 = new HashSet<SoruSinavSecenek>();
            this.SoruSinavSeceneks3 = new HashSet<SoruSinavSecenek>();
            this.SoruSinavSeceneks4 = new HashSet<SoruSinavSecenek>();
        }
    
        public int Id { get; set; }
        public int SoruId { get; set; }
        public int SecenekId { get; set; }
        public bool DogruMu { get; set; }
    
        public virtual Secenek Secenek { get; set; }
        public virtual Soru Soru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoruSinavSecenek> SoruSinavSeceneks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoruSinavSecenek> SoruSinavSeceneks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoruSinavSecenek> SoruSinavSeceneks2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoruSinavSecenek> SoruSinavSeceneks3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoruSinavSecenek> SoruSinavSeceneks4 { get; set; }
    }
}
