//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMatik_V1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VerilerEntities : DbContext
    {
        public VerilerEntities()
            : base("name=VerilerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Der> Ders { get; set; }
        public virtual DbSet<Konu> Konus { get; set; }
        public virtual DbSet<Secenek> Seceneks { get; set; }
        public virtual DbSet<Sinav> Sinavs { get; set; }
        public virtual DbSet<Soru> Sorus { get; set; }
        public virtual DbSet<SoruSecenek> SoruSeceneks { get; set; }
        public virtual DbSet<SoruSinavSecenek> SoruSinavSeceneks { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
